"""Issue #133 on EVERY adapter - a write that returns rows commits, exactly once.

The PostgreSQL half of #133 is ``test_issue133_fetch_write_commits.py``. The
same statement shape - ``INSERT ... RETURNING`` / ``INSERT ... OUTPUT`` - goes
through fetch_one()/fetch() on every engine, and ``_is_write_statement()`` is
the cross-framework rule that decides it is a write. Measured on the lab before
the fix:

  * MSSQL and Firebird: fetch_one() returned the new id and never committed. A
    second connection could not see the row (MSSQL even blocked on its lock),
    and it was lost when the connection closed.
  * ODBC: after one explicit transaction the connection stayed in manual-commit
    mode, so the next fetch_one() write was never committed - and inside a
    transaction execute() committed each statement on its own.
  * fetch() of a write failed on every engine: the adapter paginated it (LIMIT,
    ROWS, OFFSET/FETCH), which no engine accepts after RETURNING/OUTPUT.

The contract, per engine: the write runs ONCE (exactly one row, read back
through a brand-new connection), outside a transaction it is committed like
execute(), inside one nothing is visible until commit().

NO MOCKS: real SQLite, PostgreSQL, MSSQL, Firebird and ODBC (psqlODBC) servers.
Every check opens a FRESH connection: Firebird reads from a snapshot, so a
long-lived observer would not see a later commit even when it happened.
"""
import os
import socket
from urllib.parse import urlparse

import pytest

TABLE = "issue133_py_{engine}"


def _reachable(url: str, default_port: int) -> bool:
    parsed = urlparse(url)
    try:
        with socket.create_connection((parsed.hostname or "localhost", parsed.port or default_port), timeout=1.0):
            return True
    except OSError:
        return False


def _odbc_url():
    dsn = os.environ.get("TINA4_TEST_ODBC_DSN")
    return f"odbc:///{dsn}" if dsn else None


ENGINES = {
    "sqlite": {
        "url": None,  # a file under tmp_path, filled in by the fixture
        "create": "CREATE TABLE {t} (id INTEGER PRIMARY KEY AUTOINCREMENT, note TEXT)",
        "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id",
        "count": "SELECT count(*) AS n FROM {t}",
        "drop": "DROP TABLE IF EXISTS {t}",
    },
    "postgres": {
        "url": os.environ.get("TINA4_TEST_PG_URL"), "port": 5432, "service": "PostgreSQL",
        "create": "CREATE TABLE {t} (id serial PRIMARY KEY, note text)",
        "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id",
        "count": "SELECT count(*) AS n FROM {t}",
        "drop": "DROP TABLE IF EXISTS {t}",
        "before_drop": "SET lock_timeout = '10s'",
    },
    "mssql": {
        "url": os.environ.get("TINA4_TEST_MSSQL_URL"), "port": 1433, "service": "MSSQL",
        "create": "CREATE TABLE {t} (id INT IDENTITY(1,1) PRIMARY KEY, note VARCHAR(50))",
        "write": "INSERT INTO {t} (note) OUTPUT INSERTED.id VALUES (?)",
        # READPAST: an uncommitted row is skipped instead of blocking the reader
        # on its lock, so "not committed" reads as 0 rather than hanging.
        "count": "SELECT count(*) AS n FROM {t} WITH (READPAST)",
        "drop": "IF OBJECT_ID('{t}') IS NOT NULL DROP TABLE {t}",
        "before_drop": "SET LOCK_TIMEOUT 10000",
    },
    "firebird": {
        "url": os.environ.get("TINA4_TEST_FIREBIRD_URL"), "port": 3050, "service": "Firebird",
        "create": "CREATE TABLE {t} (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note VARCHAR(50))",
        "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id",
        "count": "SELECT count(*) AS n FROM {t}",
        "drop": None,  # Firebird has no DROP TABLE IF EXISTS; table_exists() guards it
    },
    "odbc": {
        "url": _odbc_url(), "port": None, "service": "ODBC",
        "create": "CREATE TABLE {t} (id serial PRIMARY KEY, note text)",
        "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id",
        "count": "SELECT count(*) AS n FROM {t}",
        "drop": "DROP TABLE IF EXISTS {t}",
        # A connection a red run leaves idle in transaction must fail the DROP,
        # not hang the whole run on its lock.
        "before_drop": "SET lock_timeout = '10s'",
    },
}


class Engine:
    """One real engine: connect, count through a fresh connection, clean up."""

    def __init__(self, name, spec, url):
        self.name, self.spec, self.url = name, spec, url
        self.table = TABLE.format(engine=name)
        self.write = spec["write"].format(t=self.table)
        self.plain_insert = f"INSERT INTO {self.table} (note) VALUES (?)"
        self._open = []

    def connect(self):
        from tina4_python.database import Database
        database = Database(self.url)
        self._open.append(database)
        return database

    def committed_rows(self) -> int:
        """Rows a brand-new connection can see - i.e. rows that were committed."""
        from tina4_python.database import Database
        fresh = Database(self.url)
        try:
            row = fresh.fetch_one(self.spec["count"].format(t=self.table), [], no_cache=True)
            return int(row["n"])
        finally:
            fresh.close()

    def drop(self):
        from tina4_python.database import Database
        database = Database(self.url)
        try:
            if self.spec.get("before_drop"):
                database.execute(self.spec["before_drop"])
            if self.spec["drop"]:
                database.execute(self.spec["drop"].format(t=self.table))
            elif database.table_exists(self.table):
                database.execute(f"DROP TABLE {self.table}")
            database.commit()
        finally:
            database.close()

    def close_all(self):
        for database in self._open:
            try:
                database.close()
            except Exception:
                pass
        self._open.clear()


@pytest.fixture(params=list(ENGINES))
def engine(request, tmp_path):
    name = request.param
    spec = ENGINES[name]
    url = f"sqlite:///{tmp_path}/issue133.db" if name == "sqlite" else spec["url"]
    if not url:
        pytest.skip(f"[needs:{name}] {spec['service']} not configured for the #133 adapter test (env var not set)")
    if spec.get("port") and not _reachable(url, spec["port"]):
        pytest.skip(f"[needs:{name}] {spec['service']} not reachable - skip integration test")
    current = Engine(name, spec, url)
    current.drop()
    setup = current.connect()
    setup.execute(spec["create"].format(t=current.table))
    setup.commit()
    current.close_all()
    yield current
    current.close_all()
    current.drop()


def test_fetch_one_write_is_committed_exactly_once(engine):
    writer = engine.connect()
    row = writer.fetch_one(engine.write, ["one"])
    assert row and row["id"] == 1, f"{engine.name}: the write did not return its id: {row!r}"
    assert engine.committed_rows() == 1, (
        f"{engine.name}: fetch_one() returned the new id, but a fresh connection "
        "does not see exactly one committed row (#133)"
    )


def test_fetch_one_write_after_an_explicit_transaction_is_committed(engine):
    writer = engine.connect()
    writer.start_transaction()
    writer.execute(engine.plain_insert, ["in transaction"])
    writer.commit()
    row = writer.fetch_one(engine.write, ["after the transaction"])
    assert row and row["id"] == 2
    assert engine.committed_rows() == 2, (
        f"{engine.name}: a write through fetch_one() after an explicit transaction "
        "was never committed (#133)"
    )


def test_nothing_is_committed_inside_an_explicit_transaction_until_commit(engine):
    """Negative case: the caller owns the boundary of an explicit transaction."""
    writer = engine.connect()
    writer.start_transaction()
    writer.execute(engine.plain_insert, ["pending"])
    writer.fetch_one(engine.write, ["pending too"])
    assert engine.committed_rows() == 0, (
        f"{engine.name}: a write became visible inside the caller's transaction, before commit()"
    )
    writer.commit()
    assert engine.committed_rows() == 2


def test_fetch_of_a_write_runs_once_with_no_count_probe_or_pagination(engine):
    """fetch() must run a write exactly as written: no COUNT probe around it and
    no LIMIT / ROWS / OFFSET-FETCH after it. Paginating a write is a syntax error
    on every engine, and a probe that did run would perform the write twice."""
    writer = engine.connect()
    result = writer.fetch(engine.write, ["via fetch"], limit=1)
    assert result.records == [{"id": 1}], f"{engine.name}: fetch() of a write returned {result.records!r}"
    assert result.count == 1
    assert engine.committed_rows() == 1, f"{engine.name}: fetch() of a write did not commit exactly one row"
