"""RS256-is-opt-in / HMAC-is-the-standard regression tests.

The ruling these pin (maintainer, 2026-08-01):

  1. HMAC (HS256/HS384/HS512) is THE Tina4 JWT algorithm family, zero-dependency
     in all four frameworks. In Python that means hmac + hashlib and nothing else.
  2. RS256 is OPT-IN. Python's standard library has no asymmetric crypto at all,
     so RS256 needs the ``cryptography`` package - which Tina4 never declares as a
     dependency. The check is LAZY: it fires only when a caller actually signs or
     verifies with RS256, never at import, boot or construction.
  3. Where RS256 is unavailable it fails LOUDLY and ACTIONABLY, naming the package
     and the install command. Never a silent fallback, never a mysterious ``None``.
  4. Algorithm pinning is UNWEAKENED: under an HMAC configuration a token whose
     header claims RS256 is rejected, and ``alg: "none"`` stays rejected.

NO DOUBLES ANYWHERE. The "library absent" state is not simulated with a stub, a
monkeypatch or a fake module - it is produced by running a REAL interpreter with
``-S``, which skips ``site.py`` so site-packages never joins ``sys.path`` and every
third-party package is genuinely unimportable. Every isolated child asserts a
CONTROL first: ``pytest`` IS installed in this environment, so if the child can
still see pytest the isolation did nothing and the test fails instead of passing
for the wrong reason.
"""
import base64
import importlib.util
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

from tina4_python.auth import Auth, RS256UnavailableError

SECRET = "rs256-optin-regression-secret"
REPO_ROOT = str(Path(__file__).resolve().parent.parent)

# Stands in for the RSA PUBLIC key an RS256 verifier is configured with. It is
# deliberately public knowledge - that is the whole premise of the confusion
# attack below, and no test here needs it to be a parseable key, because every
# one of them is rejected at the algorithm pin before any key parsing happens.
PUBLIC_KEY_STANDIN = "-----BEGIN PUBLIC KEY-----\nPUBLIC-BY-DESIGN\n-----END PUBLIC KEY-----"

# Whether THIS environment can do RS256 at all. Used to branch, never to skip:
# both branches assert something real, so the test is a gate in either state.
CRYPTOGRAPHY_INSTALLED = importlib.util.find_spec("cryptography") is not None


def _b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def _header(alg: str) -> str:
    return _b64(json.dumps({"alg": alg, "typ": "JWT"}).encode())


def _token_alg(token: str):
    """The ``alg`` a token's own header claims, or None if it has no readable one.

    Needed to tell the two RS256 rejection paths apart. ``valid_token`` pins the
    algorithm to the CONFIGURED one before any signature work, so a token whose
    header claims something else is refused without the RSA backend ever being
    consulted. Only a token whose header alg matches the pin actually reaches
    ``_rs256_verify`` and therefore the capability check.
    """
    try:
        raw = token.split(".")[0]
        return json.loads(base64.urlsafe_b64decode(raw + "=" * (-len(raw) % 4))).get("alg")
    except Exception:
        return None


def _run_child(body: str, isolated: bool) -> str:
    """Run source in a REAL child interpreter and return its stdout.

    isolated=True adds ``-S``: no site.py, therefore no site-packages on
    sys.path, therefore ``cryptography`` is genuinely not importable. This is an
    interpreter configuration, not a test double - nothing stands in for the
    package, the package is simply not there.
    """
    argv = [sys.executable] + (["-S"] if isolated else []) + ["-c", textwrap.dedent(body)]
    proc = subprocess.run(
        argv,
        env={**os.environ, "PYTHONPATH": REPO_ROOT, "TINA4_SECRET": SECRET},
        capture_output=True, text=True, timeout=120,
    )
    assert proc.returncode == 0, (
        f"child interpreter failed (isolated={isolated})\n"
        f"--- stdout ---\n{proc.stdout}\n--- stderr ---\n{proc.stderr}"
    )
    return proc.stdout


# The control every isolated child runs first. pytest is installed (we are running
# under it), so its ABSENCE in the child proves site-packages really is gone.
_CONTROL = """
        import importlib.util, sys
        assert importlib.util.find_spec("pytest") is None, (
            "CONTROL FAILED: pytest is still importable, so site-packages was NOT "
            "removed and the 'library absent' state was never actually produced")
        assert importlib.util.find_spec("cryptography") is None
"""


def _rsa_keypair():
    """A real 2048-bit RSA keypair, generated by the same library RS256 uses.

    Only ever called in the branch where cryptography is installed.
    """
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    public_pem = key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()
    return private_pem, public_pem


# ── 1. HMAC is the standard, and it is genuinely zero-dependency ──────────────

def test_hmac_family_round_trips_in_an_interpreter_with_no_site_packages():
    """POSITIVE: the DEFAULT path needs nothing but the standard library.

    Runs the whole HS256/HS384/HS512 sign+verify cycle in an interpreter that
    cannot import a single third-party package. If any part of the HMAC path ever
    reaches for cryptography (or anything else off PyPI) this dies here.
    """
    out = _run_child(_CONTROL + """
        from tina4_python.auth import Auth
        for alg in ("HS256", "HS384", "HS512"):
            auth = Auth(secret="zero-dep-secret", algorithm=alg)
            token = auth.get_token({"user_id": 9})
            payload = auth.valid_token(token)
            assert payload is not None and payload["user_id"] == 9, alg

            # NEGATIVE in the same interpreter: a tampered signature is refused.
            head, mid, sig = token.split(".")
            flipped = sig[:-1] + ("a" if sig[-1] != "a" else "b")
            assert auth.valid_token(f"{head}.{mid}.{flipped}") is None, alg

            # NEGATIVE: another secret never validates.
            assert Auth(secret="not-the-secret", algorithm=alg).valid_token(token) is None, alg
        print("HMAC-ZERO-DEP-OK")
    """, isolated=True)
    assert "HMAC-ZERO-DEP-OK" in out


def test_the_hmac_path_never_imports_the_rs256_backend():
    """NEGATIVE: no eager probe. Using HMAC must not pull cryptography in.

    Run WITH site-packages available, so when cryptography is installed this can
    genuinely fail. The whole point of the ruling is that the HMAC majority pays
    nothing - not an import, not a warning - for a feature they never touch.
    """
    out = _run_child("""
        import sys
        import tina4_python.auth as auth_module
        assert "cryptography" not in sys.modules, "importing tina4_python.auth pulled in cryptography"
        for alg in ("HS256", "HS384", "HS512"):
            auth = auth_module.Auth(secret="s", algorithm=alg)
            assert auth.valid_token(auth.get_token({"user_id": 1})) is not None
        assert "cryptography" not in sys.modules, "the HMAC path imported cryptography"
        import importlib.util
        print("BACKEND-INSTALLED" if importlib.util.find_spec("cryptography") else "BACKEND-ABSENT")
        print("HMAC-CLEAN-OK")
    """, isolated=False)
    assert "HMAC-CLEAN-OK" in out


# ── 2. RS256 absent: loud, actionable, at the point of use ───────────────────

def test_rs256_without_a_backend_raises_naming_the_package_and_the_command():
    """NEGATIVE: the missing-backend error names the fix, for BOTH sign and verify.

    Verification is the half that matters most. Returning None there would be
    indistinguishable from "that token is invalid", so a missing deployment
    dependency would be debugged as an authentication failure - the mysterious
    false this ruling exists to abolish.
    """
    out = _run_child(_CONTROL + """
        import base64, json
        from tina4_python.auth import Auth, RS256UnavailableError

        def b64(raw): return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()

        auth = Auth(secret="-----BEGIN PRIVATE KEY-----\\nx\\n-----END PRIVATE KEY-----",
                    algorithm="RS256")

        try:
            auth.get_token({"user_id": 1})
        except RS256UnavailableError as exc:
            sign_message = str(exc)
        else:
            raise AssertionError("signing with RS256 and no backend did not raise")

        # A well-formed RS256-headered token, so validation reaches the signature
        # check instead of bailing out on a malformed token.
        token = f"{b64(json.dumps({'alg': 'RS256', 'typ': 'JWT'}).encode())}." \\
                f"{b64(json.dumps({'user_id': 1}).encode())}.AAAA"
        try:
            result = auth.valid_token(token)
        except RS256UnavailableError as exc:
            verify_message = str(exc)
        else:
            raise AssertionError(
                f"verifying RS256 with no backend returned {result!r} instead of raising - "
                "a deployment fault silently reported as an invalid token")

        for message in (sign_message, verify_message):
            assert "cryptography" in message
            assert "pip install cryptography" in message, message
            assert "RS256" in message
            assert "HS256" in message, "the error must offer the zero-dependency alternative"
        print("RS256-ABSENT-LOUD-OK")
    """, isolated=True)
    assert "RS256-ABSENT-LOUD-OK" in out


def test_rs256_capability_is_checked_only_at_the_point_of_use():
    """NEGATIVE: no import-time, boot-time or construction-time probe.

    "Only if the user is trying to use RS256" is a hard constraint. Importing the
    module, and even constructing an Auth configured for RS256, must not raise,
    warn or log - the check belongs in sign/verify and nowhere else.
    """
    out = _run_child(_CONTROL + """
        import sys
        import tina4_python.auth as auth_module          # must not raise or probe
        assert "cryptography" not in sys.modules

        auth = auth_module.Auth(secret="pem-goes-here", algorithm="RS256")   # must not raise
        assert auth.algorithm == "RS256"

        # HMAC in the same process is completely unaffected by the RS256 config.
        hs = auth_module.Auth(secret="s", algorithm="HS256")
        assert hs.valid_token(hs.get_token({"user_id": 2}))["user_id"] == 2
        print("RS256-LAZY-OK")
    """, isolated=True)
    assert "RS256-LAZY-OK" in out


def test_rs256_is_a_recognised_algorithm_name_without_a_backend_present(monkeypatch):
    """POSITIVE + NEGATIVE CONTROL: RS256 must RESOLVE as a configured name.

    This is the control that stops "delete RS256 entirely" from looking like a
    successful implementation of "RS256 is optional": if the name stops resolving,
    this fails.
    """
    assert Auth(secret="x", algorithm="RS256").algorithm == "RS256"
    monkeypatch.setenv("TINA4_JWT_ALGORITHM", "RS256")
    assert Auth(secret="x").algorithm == "RS256"


def test_unknown_algorithm_still_raises_naming_hmac_and_rs256():
    """NEGATIVE: an algorithm we do not recognise at all still fails loudly.

    Making RS256 optional must not re-open python#106, where an unreadable
    TINA4_JWT_ALGORITHM silently downgraded to HS256.
    """
    with pytest.raises(ValueError) as excinfo:
        Auth(secret=SECRET, algorithm="banana")
    message = str(excinfo.value)
    for expected in ("HS256", "HS384", "HS512", "RS256", "TINA4_JWT_ALGORITHM"):
        assert expected in message, f"{expected!r} missing from {message!r}"


def test_the_error_type_is_exported_and_catchable_as_a_runtime_error():
    """The cross-framework contract: one importable, catchable type.

    Python is API-design master (ADR-0004), so this name and base class are what
    PHP, Ruby and Node align to.
    """
    from tina4_python import auth as auth_module
    assert "RS256UnavailableError" in auth_module.__all__
    assert issubclass(RS256UnavailableError, RuntimeError)


def test_the_cross_framework_jwt_contract_fixture_is_honoured():
    """CONFORMANCE: the wire contract a REAL client of any Tina4 app speaks.

    tests/fixtures/jwt_cross_framework.json is a byte-identical copy of the file
    in tina4-nodejs, tina4-php and tina4-ruby (same convention as
    adapter_contract.json). The tokens were minted by tina4-nodejs with
    node:crypto; nothing here re-implements JWT, so agreement is real interop and
    not two copies of the same bug.

    Every `accept` entry must validate and yield the same claims; every `reject`
    entry must be refused. Both directions matter: an accept-only fixture would
    pass on an implementation that accepts everything.
    """
    fixture = json.loads(
        Path(REPO_ROOT, "tests", "fixtures", "jwt_cross_framework.json").read_text(encoding="utf-8")
    )

    # POSITIVE control: the fixture really was read and really has both halves.
    assert len(fixture["accept"]) >= 4, "the fixture lost its accept entries"
    assert len(fixture["reject"]) >= 10, "the fixture lost its reject entries"
    assert fixture["wrongSecret"] != fixture["hmacSecret"]
    assert "PRIVATE KEY" not in json.dumps(fixture), "a private key leaked into the fixture"

    for entry in fixture["accept"]:
        key = fixture[entry["key"]]
        if entry["algorithm"] == "RS256" and not CRYPTOGRAPHY_INSTALLED:
            # RS256 is opt-in: with no backend the contract is a LOUD failure,
            # not a quiet rejection. Still an assertion, never a skip.
            with pytest.raises(RS256UnavailableError):
                Auth(secret=key, algorithm="RS256").valid_token(entry["token"])
            continue
        payload = Auth(secret=key, algorithm=entry["algorithm"]).valid_token(entry["token"])
        assert payload is not None, f"fixture accept rejected: {entry['name']}"
        assert payload == fixture["expectedPayload"], f"claims differ: {entry['name']}"

    reached_the_rsa_backend = False
    for entry in fixture["reject"]:
        key = fixture[entry["key"]]
        if entry["algorithm"] == "RS256" and not CRYPTOGRAPHY_INSTALLED:
            verifier = Auth(secret=key, algorithm="RS256")
            if _token_alg(entry["token"]) == "RS256":
                # The token's header matches the pin, so verification really does
                # reach the RSA backend. With none installed the contract is a
                # LOUD failure, not a quiet rejection. Still an assertion, never
                # a skip.
                with pytest.raises(RS256UnavailableError):
                    verifier.valid_token(entry["token"])
                reached_the_rsa_backend = True
            else:
                # The header claims a DIFFERENT algorithm, so the pin refuses the
                # token before any signature work and the RSA backend is never
                # consulted -- deliberately (valid_token: "an RS256-labelled token
                # can never drive an HMAC-configured app into the RS256 capability
                # check", and the same holds mirrored). Refusal here is None, which
                # is exactly what the fixture demands of a `reject` entry; turning
                # it into a raise would let an attacker-chosen header steer the app
                # into a deployment-error path it did not choose.
                assert verifier.valid_token(entry["token"]) is None, (
                    f"fixture reject ACCEPTED: {entry['name']}"
                )
            continue
        assert Auth(secret=key, algorithm=entry["algorithm"]).valid_token(entry["token"]) is None, (
            f"fixture reject ACCEPTED: {entry['name']}"
        )

    # ANTI-VACUITY: with no RSA backend the loud-failure branch above must have
    # actually run, otherwise a fixture that lost its RS256-headered reject entry
    # would leave the capability contract untested while still reading PASS.
    if not CRYPTOGRAPHY_INSTALLED:
        assert reached_the_rsa_backend, (
            "no reject entry exercised the RS256 capability check"
        )


def test_rs256_never_becomes_a_declared_dependency():
    """NEGATIVE: the default install stays zero-dependency, forever.

    The whole ruling collapses if someone "fixes" the missing backend by adding
    it to the manifest - including as an optional extra that a plain sync pulls in.
    """
    pyproject = Path(REPO_ROOT, "pyproject.toml").read_text(encoding="utf-8")
    assert "dependencies = []" in pyproject, "core dependencies are no longer empty"
    assert "cryptography" not in pyproject, "cryptography was declared in pyproject.toml"


# ── 3. RS256 present: it actually works, with a public-key-only verifier ─────

def test_rs256_signs_and_verifies_when_a_backend_is_installed():
    """POSITIVE (backend installed) / NEGATIVE (backend absent) - never a skip.

    With cryptography present this proves the whole point of RS256: the verifier
    holds ONLY the public key and can still check the signature. Without it, the
    same test asserts the loud error instead, so it gates in either environment.
    """
    if not CRYPTOGRAPHY_INSTALLED:
        auth = Auth(secret="pem", algorithm="RS256")
        with pytest.raises(RS256UnavailableError):
            auth.get_token({"user_id": 1})
        return

    private_pem, public_pem = _rsa_keypair()
    signer = Auth(secret=private_pem, algorithm="RS256")
    token = signer.get_token({"user_id": 42, "role": "admin"})

    head, mid, sig = token.split(".")
    assert json.loads(base64.urlsafe_b64decode(head + "=" * (-len(head) % 4)))["alg"] == "RS256"
    # 2048-bit RSA produces a 256-byte signature; no HMAC digest is that size, so
    # this cannot pass if the token was secretly signed with HMAC.
    assert len(base64.urlsafe_b64decode(sig + "=" * (-len(sig) % 4))) == 256

    verifier = Auth(secret=public_pem, algorithm="RS256")   # PUBLIC key only
    payload = verifier.valid_token(token)
    assert payload is not None and payload["user_id"] == 42 and payload["role"] == "admin"

    # NEGATIVE: a tampered payload is rejected.
    forged = _b64(json.dumps({"user_id": 99, "role": "admin"}).encode())
    assert verifier.valid_token(f"{head}.{forged}.{sig}") is None

    # NEGATIVE: an unrelated public key never validates this token.
    _, other_public = _rsa_keypair()
    assert Auth(secret=other_public, algorithm="RS256").valid_token(token) is None


def test_an_hmac_configured_verifier_rejects_a_genuine_rs256_token():
    """NEGATIVE: a real, correctly-signed RS256 token is still refused by an
    HMAC-configured app. Being cryptographically valid is not enough - it has to
    be the algorithm this app chose."""
    if not CRYPTOGRAPHY_INSTALLED:
        with pytest.raises(RS256UnavailableError):
            Auth(secret="pem", algorithm="RS256").get_token({"user_id": 1})
        return

    private_pem, _ = _rsa_keypair()
    rs_token = Auth(secret=private_pem, algorithm="RS256").get_token({"user_id": 42})
    assert Auth(secret=SECRET, algorithm="HS256").valid_token(rs_token) is None


# ── 4. Algorithm pinning: the classic JWT attack, unweakened ─────────────────

def test_hmac_configured_auth_rejects_a_token_whose_header_claims_rs256():
    """NEGATIVE: algorithm substitution. Re-labelling an HMAC token's header as
    RS256 must not validate it, and must not raise either - pinning happens
    BEFORE any signature or capability work, so a stranger's header can never
    steer an HMAC app into the RS256 backend path."""
    auth = Auth(secret=SECRET, algorithm="HS256")
    token = auth.get_token({"user_id": 7})
    _, mid, sig = token.split(".")

    assert auth.valid_token(f"{_header('RS256')}.{mid}.{sig}") is None
    assert auth.valid_token(token) is not None      # untampered still valid


def test_alg_none_is_rejected_under_hmac_configuration():
    """NEGATIVE: the unsigned-token attack. alg "none" stays refused, with a
    signature, with an empty signature, and with the signature segment gone."""
    auth = Auth(secret=SECRET, algorithm="HS256")
    token = auth.get_token({"user_id": 7})
    _, mid, sig = token.split(".")

    assert auth.valid_token(f"{_header('none')}.{mid}.{sig}") is None
    assert auth.valid_token(f"{_header('none')}.{mid}.") is None
    assert auth.valid_token(f"{_header('none')}.{mid}") is None


def test_alg_pinning_holds_even_when_rs256_is_impossible():
    """NEGATIVE, in an interpreter where RS256 CANNOT work.

    This is the sharpest form of the pinning gate. If the header check were ever
    moved after the signature check, an RS256-labelled token would drive the
    capability check and raise RS256UnavailableError - a remote-triggerable 500
    on an app that never opted into RS256. It must quietly return None instead.
    """
    out = _run_child(_CONTROL + """
        import base64, json
        from tina4_python.auth import Auth, RS256UnavailableError

        def b64(raw): return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()

        auth = Auth(secret="hmac-secret", algorithm="HS256")
        token = auth.get_token({"user_id": 7})
        head, mid, sig = token.split(".")

        for forged_alg in ("RS256", "none", "HS512"):
            forged = f"{b64(json.dumps({'alg': forged_alg, 'typ': 'JWT'}).encode())}.{mid}.{sig}"
            try:
                assert auth.valid_token(forged) is None, forged_alg
            except RS256UnavailableError:
                raise AssertionError(
                    "alg pinning was bypassed: a header claiming " + forged_alg +
                    " reached the RS256 capability check on an HMAC-configured app")
        assert auth.valid_token(token) is not None
        print("ALG-PINNING-OK")
    """, isolated=True)
    assert "ALG-PINNING-OK" in out


def test_rs256_configured_auth_pins_the_algorithm_before_any_backend_work():
    """NEGATIVE, the mirror image: an app that DID opt into RS256 still refuses
    HMAC-labelled and alg-none tokens. True whether or not a backend exists,
    because pinning runs first."""
    auth = Auth(secret=PUBLIC_KEY_STANDIN, algorithm="RS256")
    hs_token = Auth(secret=SECRET, algorithm="HS256").get_token({"user_id": 7})
    _, mid, sig = hs_token.split(".")

    assert auth.valid_token(hs_token) is None
    assert auth.valid_token(f"{_header('none')}.{mid}.{sig}") is None


@pytest.mark.parametrize(
    "honest,smuggled",
    [("HS256", "none"), ("HS256", "RS256"), ("HS512", "HS256"), ("HS384", "HS512")],
)
def test_a_correctly_signed_token_whose_header_parses_as_another_alg_is_rejected(honest, smuggled):
    """NEGATIVE: the ONE construction that gates the algorithm-pin line itself.

    Measured, not assumed: every OTHER substitution case in this file is refused
    even by an implementation with no pin at all, because the header is part of
    the HMAC signing input - relabel it and the recomputed signature simply stops
    matching. Deleting the ``header.get("alg") != self.algorithm`` comparison and
    re-running this module was still green until this test existed.

    Here the header BYTES are identical between signing and verifying, so the
    signature genuinely verifies - but the header carries ``alg`` TWICE, and
    Python's json.loads, PHP's json_decode, Ruby's JSON.parse and JS's JSON.parse
    all take the LAST duplicate key. The token therefore PARSES as the smuggled
    algorithm while carrying a valid signature, and only a verifier that compares
    the parsed alg against its OWN configuration rejects it.

    It is a real split-brain shape, not a synthetic one: a gateway that
    pre-validates on the first ``alg`` and a backend that acts on the last are
    looking at two different tokens.
    """
    import hashlib
    import hmac as hmac_module

    digest = {"HS256": hashlib.sha256, "HS384": hashlib.sha384, "HS512": hashlib.sha512}[honest]
    payload = _b64(json.dumps({"user_id": 42, "exp": 4102444800}).encode())
    # Header bytes name `honest` FIRST and `smuggled` LAST.
    raw_header = f'{{"alg":"{honest}","alg":"{smuggled}","typ":"JWT"}}'.encode()
    header = _b64(raw_header)
    signing_input = f"{header}.{payload}"
    signature = _b64(hmac_module.new(SECRET.encode(), signing_input.encode(), digest).digest())

    # CONTROL: the header really does parse as the smuggled algorithm, and the
    # signature really is the framework's own - otherwise the rejection below
    # would prove nothing. The signature is recomputed here from stdlib hmac, so
    # it is not read back out of the code under test.
    assert json.loads(raw_header)["alg"] == smuggled
    assert signature == Auth(secret=SECRET, algorithm=honest)._sign(signing_input)

    assert Auth(secret=SECRET, algorithm=honest).valid_token(f"{signing_input}.{signature}") is None, (
        f"a validly-signed {honest} token whose header parses as {smuggled} was ACCEPTED "
        "- the algorithm pin is gone"
    )

    # The second gate shape, the one tina4-ruby already had: an honest
    # single-key header that NAMES the smuggled algorithm, with the signature
    # RE-COMPUTED over that lying header so the HMAC genuinely verifies. Only the
    # pin refuses it. (Contrast the re-labelled tokens elsewhere in this file,
    # which keep a signature computed over the honest header and therefore break
    # on the signature, pin or no pin.)
    lying = _header(smuggled)
    lying_input = f"{lying}.{payload}"
    resigned = _b64(hmac_module.new(SECRET.encode(), lying_input.encode(), digest).digest())
    assert Auth(secret=SECRET, algorithm=honest).valid_token(f"{lying_input}.{resigned}") is None, (
        f"a token advertising {smuggled}, signed correctly with the {honest} secret, was ACCEPTED"
    )

    # POSITIVE control: the same construction with ONE honest alg validates, so
    # the rejection is the pin and not the duplicate key itself.
    honest_header = _b64(json.dumps({"alg": honest, "typ": "JWT"}).encode())
    honest_input = f"{honest_header}.{payload}"
    honest_sig = _b64(hmac_module.new(SECRET.encode(), honest_input.encode(), digest).digest())
    assert Auth(secret=SECRET, algorithm=honest).valid_token(f"{honest_input}.{honest_sig}") is not None


def test_rs256_app_rejects_an_hmac_token_forged_with_its_own_public_key():
    """NEGATIVE: the RS256-to-HS256 confusion attack, in full.

    An RS256 verifier's key is PUBLIC, so an attacker can take that public key,
    use it as an HMAC SECRET, and mint a perfectly-signed HS256 token. An
    implementation that picks its verification algorithm from the TOKEN'S header
    instead of its own configuration verifies it happily and authenticates the
    attacker.

    Tina4 picks the algorithm from ``self.algorithm``, so the forged token never
    reaches an HMAC comparison at all. (That dispatch, not the header pin, is
    what this particular test gates - the pin's own gate is the duplicate-key
    test above.) Works with or without an RSA backend present.
    """
    app = Auth(secret=PUBLIC_KEY_STANDIN, algorithm="RS256")

    attacker = Auth(secret=PUBLIC_KEY_STANDIN, algorithm="HS256")
    forged = attacker.get_token({"user_id": 1, "role": "admin"})

    # Sanity: the forgery IS a valid HS256 token under that secret - the attack
    # is real, it is only the algorithm pin that stops it.
    assert attacker.valid_token(forged) is not None

    assert app.valid_token(forged) is None, (
        "an HMAC token signed with the RS256 verifier's own public key was "
        "accepted - the algorithm came from the token header, not the config")
