# Copyright (c) 2026 Code Infinity
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""execute() returns the rows of any statement that produces them - on every engine.

Maintainer decision, the contract for all four frameworks (PHP already did it):
``execute(sql, params)`` of a statement that returns rows - a SELECT, a
``WITH ... SELECT``, ``INSERT/UPDATE/DELETE ... RETURNING`` (MSSQL ``OUTPUT``) -
returns a ``DatabaseResult`` carrying those rows, the same type fetch() returns.
It runs exactly once: no COUNT probe, no LIMIT/OFFSET. A write that returns no
rows keeps its old return value (``True``). Writes commit as before, and on
PostgreSQL a read leaves no transaction open.

Measured before the fix: PostgreSQL read rows only after RETURNING, so
``execute(SELECT)`` came back EMPTY; ``WITH ... SELECT`` returned ``True`` on every
engine; MSSQL dropped its OUTPUT rows (the SCOPE_IDENTITY probe ran over them);
Firebird stripped RETURNING and looked for a GEN_<TABLE>_ID generator, so an
IDENTITY table returned nothing; SQLite and ODBC never read a result set at all.

NO MOCKS: real SQLite, PostgreSQL, MySQL, MSSQL, Firebird and ODBC (psqlODBC).
Row counts are read back through a brand-new connection.
"""
import os
import socket
from urllib.parse import urlparse

import pytest

from tina4_python.database.adapter import DatabaseResult

TABLE = "exec_rows_py_{engine}"


def _odbc_url():
    dsn = os.environ.get("TINA4_TEST_ODBC_DSN")
    return f"odbc:///{dsn}" if dsn else None


ENGINES = {
    "sqlite": {"url": None, "id": "INTEGER PRIMARY KEY AUTOINCREMENT",
               "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id"},
    "postgres": {"url": os.environ.get("TINA4_TEST_PG_URL"), "port": 5432, "service": "PostgreSQL",
                 "id": "serial PRIMARY KEY", "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id"},
    "mysql": {"url": os.environ.get("TINA4_TEST_MYSQL_URL"), "port": 3306, "service": "MySQL",
              "id": "INT AUTO_INCREMENT PRIMARY KEY",
              # MySQL has no RETURNING; the adapter emulates it by re-selecting the row.
              "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id"},
    "mssql": {"url": os.environ.get("TINA4_TEST_MSSQL_URL"), "port": 1433, "service": "MSSQL",
              "id": "INT IDENTITY(1,1) PRIMARY KEY", "write": "INSERT INTO {t} (note) OUTPUT INSERTED.id VALUES (?)"},
    "firebird": {"url": os.environ.get("TINA4_TEST_FIREBIRD_URL"), "port": 3050, "service": "Firebird",
                 "id": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                 "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id"},
    "odbc": {"url": _odbc_url(), "port": None, "service": "ODBC",
             "id": "serial PRIMARY KEY", "write": "INSERT INTO {t} (note) VALUES (?) RETURNING id"},
}


def _reachable(url, port) -> bool:
    parsed = urlparse(url)
    try:
        with socket.create_connection((parsed.hostname or "localhost", parsed.port or port), timeout=1.0):
            return True
    except OSError:
        return False


class Engine:
    def __init__(self, name, url):
        from tina4_python.database import Database
        self.name, self.url, self.spec = name, url, ENGINES[name]
        self.table = TABLE.format(engine=name)
        self.db = Database(url)

    def committed_rows(self) -> int:
        from tina4_python.database import Database
        fresh = Database(self.url)
        try:
            return int(fresh.fetch_one(f"SELECT count(*) AS n FROM {self.table}", no_cache=True)["n"])
        finally:
            fresh.close()

    def drop(self):
        from tina4_python.database import Database
        database = Database(self.url)
        try:
            if database.table_exists(self.table):
                database.execute(f"DROP TABLE {self.table}")
                database.commit()
        finally:
            database.close()


@pytest.fixture(params=list(ENGINES))
def engine(request, tmp_path):
    name = request.param
    spec = ENGINES[name]
    url = f"sqlite:///{tmp_path}/exec_rows.db" if name == "sqlite" else spec["url"]
    if not url:
        pytest.skip(f"[needs:{name}] {spec['service']} not configured for the execute-rows test (env var not set)")
    if spec.get("port") and not _reachable(url, spec["port"]):
        pytest.skip(f"[needs:{name}] {spec['service']} not reachable - skip integration test")
    Engine(name, url).drop()
    current = Engine(name, url)
    current.db.execute(f"CREATE TABLE {current.table} (id {spec['id']}, note VARCHAR(20))")
    current.db.commit()
    for note in ("one", "two", "three"):
        current.db.execute(f"INSERT INTO {current.table} (note) VALUES (?)", [note])
    yield current
    current.db.close()
    current.drop()


def _ids(records):
    return [int(row["id"]) for row in records]


def test_execute_select_with_a_param_returns_the_same_rows_as_fetch(engine):
    sql = f"SELECT id, note FROM {engine.table} WHERE id >= ? ORDER BY id"
    result = engine.db.execute(sql, [2])
    assert isinstance(result, DatabaseResult), f"{engine.name}: execute(SELECT) returned {result!r}"
    assert result.records == engine.db.fetch(sql, [2], no_cache=True).records
    assert _ids(result.records) == [2, 3] and result.count == 2


def test_execute_select_with_no_matching_rows_is_still_a_result(engine):
    result = engine.db.execute(f"SELECT id FROM {engine.table} WHERE id > ?", [100])
    assert isinstance(result, DatabaseResult), f"{engine.name}: an empty SELECT returned {result!r}"
    assert result.records == [] and result.count == 0


def test_execute_with_select_returns_its_rows(engine):
    result = engine.db.execute(
        f"WITH later AS (SELECT id FROM {engine.table} WHERE id > ?) SELECT id FROM later ORDER BY id", [1],
    )
    assert isinstance(result, DatabaseResult), f"{engine.name}: execute(WITH ... SELECT) returned {result!r}"
    assert _ids(result.records) == [2, 3]


def test_execute_write_returning_returns_the_id_and_writes_exactly_once(engine):
    result = engine.db.execute(engine.spec["write"].format(t=engine.table), ["four"])
    assert isinstance(result, DatabaseResult), f"{engine.name}: {result!r}"
    assert _ids(result.records) == [4], f"{engine.name}: the returned rows were {result.records!r}"
    assert engine.committed_rows() == 4, f"{engine.name}: the write did not land exactly once"


def test_execute_update_without_returning_keeps_its_return_value(engine):
    assert engine.db.execute(f"UPDATE {engine.table} SET note = ? WHERE id = ?", ["changed", 1]) is True
    assert engine.committed_rows() == 3


def test_execute_select_leaves_no_transaction_open_on_postgres(engine):
    if engine.name != "postgres":
        return  # the idle-in-transaction symptom is PostgreSQL's; the other cases cover the rest
    from tina4_python.database import Database
    engine.db.execute(f"SELECT id FROM {engine.table} WHERE id = ?", [1])
    pid = engine.db._get_adapter()._conn.info.backend_pid
    observer = Database(engine.url)
    try:
        row = observer.fetch_one("SELECT state FROM pg_stat_activity WHERE pid = ?", [pid], no_cache=True)
    finally:
        observer.close()
    assert row["state"] == "idle", f"execute(SELECT) left the connection '{row['state']}'"
